after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

jdk:
  - oraclejdk8

language: java

script:
  - ./gradlew clean build --parallel --stacktrace

sudo: false
